services:
  calorie-api:
    image: pytorch/pytorch:latest
    container_name: calorie-clip-server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install -r requirements.txt && 
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
